privacy info (draft)
Xceptance/xlt-documentation pull request #181
Opened 2023-03-09 13:32 UTC by js-xc

2023-03-10 09:07 UTC, rschwietzke requested changes

2023-03-10 09:07 UTC, rschwietzke commented on content/en/xtc/privacy/_index.md
> +XTC does not do automated account management (i.e. deactivation of accounts).
Accounts don't expire currently, only open and unaccepted invocations will (soon) expire.

2023-03-10 09:07 UTC, rschwietzke commented on content/en/xtc/privacy/_index.md
> +{{< TODO / >}}How long is account data/test data stored? Which can I delete myself, how, and when will this take effect?
There is no data retention for load test data. As long as an org or project exists, this data is retained. Customers have to delete this data themselves if needed.

Accounts cannot be deleted at the moment. A customer can write to support@xceptance.com and ask for system-wide deletion.

2023-03-10 10:26 UTC, js-xc commented on content/en/xtc/privacy/_index.md
> +All resources are hosted internally at _xtc.xceptance.com_.
That's true, but in that case, please explain what we are trying to say by "No external to xtc.xceptance.com hosting of resources" (see ticket).

2023-03-10 10:32 UTC, rschwietzke commented on content/en/xtc/privacy/_index.md
> +All resources are hosted internally at _xtc.xceptance.com_.
Data is not hosted by any third party and does not leave the scope of XTC. Data storage also does not use any Google services.

2023-03-21 14:54 UTC, rschwietzke requested changes

2023-03-21 14:54 UTC, rschwietzke commented on content/en/xtc/privacy/_index.md
> +In case you chose to use an [external login provider]({{< relref "../basics/040-user-accounts/#external-login-providers-sso" >}}) for authentication you will exchange data with your login provider (G
Comma: ...authentication , you will...
Remove: on external servers

2023-03-21 14:54 UTC, rschwietzke commented on content/en/xtc/privacy/_index.md
> +XTC does _not_ store any of your contractual information or payment data.
XTC does not store any of contractual information or payment data.

2023-03-21 14:54 UTC, rschwietzke commented on content/en/xtc/privacy/_index.md
> +XTC does not do automated account management (i.e. deactivation/deletion of inactive accounts). If you need to delete your account, you can write an email to support@xceptance.com to ask for a system
XTC does not perform automated account management

Please note, that audit logs will retain the name and email address for 180 days, even when your account has been deleted.

2023-03-22 13:17 UTC, js-xc commented on content/en/xtc/privacy/_index.md
> +XTC includes no external analytics services or tracking.
See below: "The information and personal data you share with us will be utilized solely for the use of XTC services." Is this about the same as "no internal use" or do you want it more explicit?

2023-03-29 14:41 UTC, rschwietzke approved these changes

2023-03-29 14:43 UTC, merged