mastercontroller.properties
Xceptance/xlt-documentation pull request #43
Opened 2021-04-16 08:44 UTC by js-xc

updated example output to XLT 5.2.0. 
added more explicit/additional info on AC configuration in mastercontroller.properties.

2021-04-16 12:49 UTC, rschwietzke requested changes

2021-04-16 13:13 UTC, js-xc commented on content/en/load-testing/Manual/310-test-execution.md
> +## Configuring the Agent Controllers
true. Originally I put this info inside "Starting the master controller", there it was more obvious.

2021-04-21 17:43 UTC, rschwietzke approved these changes

2021-04-21 17:46 UTC, rschwietzke commented
Added a few changes and suggestions. If you approve, feel free to merge. I have decided the use agentcontroller and mastercontroller as one word and not two (also change that in the glossary), because it more accurately points to our component.

2021-04-22 09:17 UTC, merged